# SPDX-FileCopyrightText: Copyright © duneuro-py contributors, see file LICENSE.md in module root
# SPDX-License-Identifier: LicenseRef-GPL-2.0-only-with-duneuro-py-exception OR LGPL-3.0-or-later
################################
# Dune module information file #
################################

#Name of the module
Module: duneuro-py
Version: 2.10-dev
Maintainer: andreas.nuessing@uni-muenster.de
#depending on
Depends: dune-common (>= 2.10) duneuro (>= 2.10)
